import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useLazyQuery, useQuery } from "@apollo/client";
import { GET_USER_SEARCH } from "../apollo/queries/search";
import { InView } from "react-intersection-observer";
import ProfileCard from "../components/ProfileCard";
import SearchForm from "../components/SearchFrom";

const PAGE_SIZE = 6;

const Home: NextPage = () => {
  const [query, setQuery] = useState<string>("");
  const [isFetchMore, setIsFetchMore] = useState(true);
  const [runSearchQuery, { called, loading, data, fetchMore }] = useLazyQuery(
    GET_USER_SEARCH,
    {
      variables: {
        first: PAGE_SIZE,
        query: query,
      },
    }
  );
  useEffect(() => {
    if (data) setIsFetchMore(data.search.pageInfo.hasNextPage);
  }, [data]);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    runSearchQuery({
      variables: {
        first: PAGE_SIZE,
        query,
      },
    });
  };
  const handleSearch = (e) => {
    setQuery(e.target.value);
  };

  return (
    <div className="py-8 bg-slate-100">
      <Head>
        <title>A nextjs app for github user search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col px-8 min-h-screen items-center justify-center">
        <h1 className="text-3xl x my-4 text-center ">
          Welcome to{" "}
          <a
            href="https://developer.github.com/v3/search/"
            className="text-blue-600"
          >
            Github user search!
          </a>
        </h1>
        <SearchForm
          query={query}
          onSearchFormSubmit={handleSubmit}
          onSearchInputChange={handleSearch}
        />

        <section className="flex items-center justify-center flex-wrap">
          {/* {data && (
            <p className="text-sm text-slate-500">
              <span className="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-sky-600 bg-sky-200 uppercase last:mr-0 mr-1">
                {data.search.userCount}
              </span>
              user found
            </p>
          )} */}
          {loading && <div>Loading.... </div>}
          {data &&
            data.search.edges.map((item: any) => (
              <ProfileCard
                key={item.node.id}
                name={item.node.name}
                avatarUrl={item.node.avatarUrl}
                location={item.node.location}
                bio={item.node.bio}
                profileUrl={item.node.url}
              />
            ))}
          {data && (
            <InView
              onChange={async (inView) => {
                if (inView) {
                  const { endCursor } = data.search.pageInfo;
                  console.log(
                    data.search.pageInfo.hasNextPage,
                    data.search.userCount,
                    data.search.edges.length
                  );
                  if (!isFetchMore) return;
                  fetchMore({
                    variables: { after: endCursor },
                    updateQuery: (prevResult, { fetchMoreResult }) => {
                      setIsFetchMore(
                        fetchMoreResult.search.pageInfo.hasNextPage
                      );
                      console.log(fetchMoreResult.search.pageInfo.hasNextPage);
                      fetchMoreResult.search.edges = [
                        ...prevResult.search.edges,
                        ...fetchMoreResult.search.edges,
                      ];
                      fetchMoreResult.search.pageInfo =
                        fetchMoreResult.search.pageInfo;
                      return fetchMoreResult;
                    },
                  });
                }
              }}
            />
          )}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
